name: Hello GitHub Actions

on:
  pull_request:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Send greeting
        run: echo "👋 Hello! Thanks for opening this pull request!"
